cargo-features = ["workspace-inheritance"]

[package]
name = "hash-graph"
description.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true


[dependencies]
graph = { path = "../../lib/graph" }
tokio = { version = "1.18.2", features = ["rt", "macros"] }
error-stack = "0.1.1"
