extend = { path = "../../.github/scripts/rust/Makefile.toml" }

[env]
CARGO_HACK_FLAGS = "--feature-powerset --features build-nng --exclude-features default --ignore-unknown-features --optional-deps clap"

[tasks.default]
alias = "run"

# The `test` task will execute these task in the folloing order:
#  1. Build the tests
#  2. Setup python
#  3. Run unit tests
#  4. Run the integration tests

[tasks.test]
clear = true
workspace = false
description = "Runs the test suite"
category = "Test"
run_task = { name = ["build-test", "setup-python", "run-test-suite", "run-integrations"] }

[tasks.build-test]
private = true
extend = "build"
args = ["build", "-p", "memory", "--profile", "${CARGO_MAKE_CARGO_PROFILE}"]

[tasks.setup-python]
private = true
script = '''
#!/usr/bin/env bash
lib/execution/src/runner/python/setup.sh python3.7
'''

[tasks.run-test-suite]
private = true
run_task = { name = "run-tests", fork = true }

[tasks.run-tests]
private = true
command = "cargo"
args = ["hack", "test", "--no-fail-fast", "@@split(CARGO_HACK_FLAGS, )", "--profile", "${CARGO_MAKE_CARGO_PROFILE}"]

[tasks.run-integrations]
private = true
command = "cargo"
args = ["test", "--workspace", "--test", "integration", "--no-fail-fast", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "--all-features"]


# Rustdoc must not be executed on the workspace root.
[tasks.doc-task-ci-public]
condition = { env_false = ["CARGO_MAKE_CRATE_IS_WORKSPACE"] }

[tasks.doc-task-ci-private]
condition = { env_false = ["CARGO_MAKE_CRATE_IS_WORKSPACE"] }
